name: Checkup

on:
  push:
    branches:
      - main
    paths:
      - ".github/scripts/checkup/**/*.*"
      - ".github/workflows/checkup.yml"
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  checkup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: main

      - uses: actions/checkout@v3
        with:
          ref: data
          path: data

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: FedericoCarboni/setup-ffmpeg@v2

      - name: Install PNPM
        working-directory: main/.github/scripts
        run: |
          npm i -g pnpm
          pnpm i

      - name: Checkup
        working-directory: main/.github/scripts
        run: node checkup/index.mjs

      - name: Convert checkup things
        working-directory: main
        run: |
          chmod +x .github/scripts/checkup/convert.sh
          .github/scripts/checkup/convert.sh

      - name: Move data directory
        run: mv -v main/data/* data/

      - name: Commit changes
        working-directory: data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "chore: emojipack checkup" | true
          git pull
          git push
